### ISSUE TITLE
Wrong MonthDays in June 2015

### ISSUE THREAD

**Issue by jblankenhorn** [w11k/trello-calendar#19]

**Comment by jblankenhorn** [comment]
![screenshot at mai 27 13-13-57](https://cloud.githubusercontent.com/assets/138586/7834726/7445c794-0472-11e5-871b-7533bcd4367b.png)

**Comment by CanKattwinkel** [comment]
fixed. 

Error popped up when first day of month was monday. wrong iteration caused pushing only 6 instead of 7 "off" days from last month to the view.
